baseURL: "https://lcscout.netlify.app"
languageCode: "en-us"
title: "Lucas Coutinho"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Lucas Coutinho - Portfolio"
  description: Hi! I'm Lucas, a game developer from Brazil and this is my personal portfolio where I post everything I do.
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
      primaryColor: "#000"
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Lucas Coutinho" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi there 👋 I'm"
    title: "Lucas,"
    subtitle: "a game developer."
    content: "I'm based on Brazil and I'm very interested in everything that surrounds game development and passionate about creating new worlds and unique experiences."
    image: /images/peep896963.png
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "/resume_outdated.pdf"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fas fa-envelope
          url: mailto:contact@lucascoutinho.me
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/lcscout/
        - icon: fab fa-github
          url: https://github.com/lcscout
        - icon: fas fa-link
          url: https://linktr.ee/lcscout
      # customIcons:
        # - icon: /fav.png
          # url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.jpg"
    content: |-
      I'm mostly a programmer but I have a strong interest in the intersection of technology and art. I'm very interested in render pipelines, shaders, software architecture and game optimizations. Currently, I work as a game developer at [Izyplay Game Studio](https://www.izyplay.com/).

      Besides work, I'm currently doing a bachelor's degree in Digital Games at PUC Minas. I'm also working on a personal project to be launched on Steam soon enough.
    skills:
      enable: true
      title: "I realize that I don't know everything and I recognize my weak points, adding it to my learning. Over the years though I've sharpen my experience in:"
      items:
        - "Unity"
        - "Mobile Development"
        - "C#"
        - "Art & UI Integration"
        - "Git"
        - "Game Tooling"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Game Developer"
        company: "Izyplay Game Studio"
        companyUrl: "https://www.izyplay.com/"
        date: "Jun 2022 - present"
        featuredLink:
          enable: true
          name: "Check our projects"
          url: "https://izyplay.com/inicial#games"
        content: |
          - Responsible for translating the game designs' ideas into gameplay features. Also responsible for creating tools to improve workflow and implementing external tools and analytics 💪
          - I have successfully contributed to a diverse range of projects, swiftly adapting to different teams and responsibilities. Moreover, I have actively participated in significant and pivotal projects, where my contributions played a crucial role in shaping and advancing the major goals of the company.
          - I developed and adapted games for a variety of platforms, mainly mobile, addressing compatibility challenges and optimizing projects to align with the distinct characteristics of each platform.
          - My role extended beyond project execution as I became an advocate for enriching the company's collective knowledge. This involved an in-depth examination of our current tech landscape as well as a vigilant exploration of new advancements. While I gained valuable insights I also shared them with the team, fostering a culture of continuous learning and growth 🧠
          - Furthermore, I contributed by documenting a diverse array of processes such as best practices and troubleshooting guides. This proved invaluable in fostering consistent approaches, aiding new team members, and enhancing overall productivity.

      - job: "Full-Stack Web Developer"
        company: "PICSIZE"
        companyUrl: "https://picsize.com.br/"
        date: "Nov 2019 - Mar 2020"
        info:
          enable: true
          content: I was an intern for 4 months and worked more 2 months part-time before quitting for personal reasons.
        content: |
          At PICSIZE, I worked with a very small team of 6 people at a startup that provides solutions for photographers' workflow, from the moment they finish taking the photo to delivering it to their clients.

          - It was my first work experience, and I had the pleasure of being in touch with wonderful people from whom I learned a lot, both technically and personally 🙏
          - After 4 months of internship I was invited to a part-time position.
          - At this point I was assigned to create a new solution on my own. The project was a portfolio creator, where photographers could easily show their work in a featured page. But ultimately, I ended up quitting the job.

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Bachelor's degree in Digital Games"
        school:
          name: "PUC Minas"
          url: "https://example.org"
        date: "2013 - 2015"

      - title: "Bachelor's degree in Control and Automation Engineering"
        school:
          name: "UFMG"
          url: "https://example.org"
        date: "2009 - 2013"
        content: |
          I 

      - title: "Bachelor's degree in Information Systems"
        school:
          name: "UFMG"
          url: "https://example.org"
        date: "2009 - 2013"

      - title: "Vocational degree in Mechanics, and High School"
        school:
          name: "IFES"
          url: "https://example.org"
        date: "2009 - 2013"
        content: |
          It was during high school that I came in contact with programming for the first time. I learned the basics of C++ Language and soon wanted to learn another one.

          - With the same will in mind a friend of mine started learning Python and I chose to learn Ruby (not my best decision 😛), just to not copycat.
          - I learned it mostly by doing games using the Gosu gem, and it was pretty fun, this was also my introduction to game programming.

  # Achievements
  achievements:
    enable: true
    title: "Highlights"
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
        image: /images/achievment.jpg
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
        image: /images/achievment.jpg
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
        image: /images/achievment.jpg
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Hugo Profile
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        image: /images/projects/profile.png
        featured:
          name: Demo
          link: https://hugo-profile.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/gurusabarish/hugo-profile
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Image Converter
        content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
        image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://django-converter.herokuapp.com
        badges:
          - "Django"
          - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

      - title: Hugo Profile V2
        content: A clean and simple Hugo template for personal portfolio and blog.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: gurusabarisha@gmail.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com
      linkedin: https://linkedin.com
      twitter: https://twitter.com
      instagram: https://instagram.com
      facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
