baseURL: "https://lcscout.netlify.app"
languageCode: "en-us"
title: "Lucas Coutinho"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blog
      weight: 1
    - identifier: gallery
      name: Gallery
      title: Gallery
      url: /gallery
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Lucas Coutinho - Portfolio"
  description: Hi! I'm Lucas, a game developer from Brazil and this is my personal portfolio where I post everything I do.
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
      primaryColor: "#000"
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Lucas Coutinho" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi there 👋 I'm"
    title: "Lucas,"
    subtitle: "a game developer."
    content: "I'm currently based on Brazil and I'm very interested in everything that surrounds game development. My passion is to create and share new worlds and unique experiences."
    image: /images/peep896963.png
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "/resume_outdated.pdf"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fas fa-envelope
          url: mailto:contact@lucascoutinho.me
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/lcscout/
        - icon: fab fa-github
          url: https://github.com/lcscout
        - icon: fas fa-link
          url: https://linktr.ee/lcscout
      # customIcons:
        # - icon: /fav.png
          # url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.jpg"
    content: |-
      I'm mostly a programmer but I have a strong interest in the intersection of technology and art. I'm very interested in render pipelines, shaders, software architecture and game optimizations. Currently, I work as a game developer at [Izyplay Game Studio](https://www.izyplay.com/).

      Besides work, I'm currently doing a bachelor's degree in Digital Games at PUC Minas. I'm also working on a personal project to be launched on Steam soon enough 👀
    skills:
      enable: true
      title: "I realize that I don't know everything and I recognize my weak points, adding it to my learning. Over the years though I've sharpen my experience in:"
      items:
        - "Unity"
        - "Mobile Development"
        - "C#"
        - "Art & UI Integration"
        - "Git"
        - "Game Tooling"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Game Developer"
        company: "Izyplay Game Studio"
        companyUrl: "https://www.izyplay.com/"
        date: "Jun 2022 - present"
        featuredLink:
          enable: true
          name: "Check our projects"
          url: "https://izyplay.com/inicial#games"
        content: |
          In this position I was primarily responsible for translating game design ideas into gameplay features, as well as creating tools to improve workflow, integrating visual elements and UI, and implementing external tools for data analysis.

          Furthermore:
          - Contributed successfully to a variety of projects, adapting easily between different teams. In addition, I actively participated in significant projects where I played a crucial role in shaping and advancing the company's key goals 💪
          - Developed and adapted games for a variety of platforms, mainly mobile, but always addressing compatibility challenges and optimizing projects for the distinct characteristics of each platform.
          - My role extended beyond the execution of projects, as I also contributed to the enrichment of the company's collective knowledge. While gaining valuable insights, I also shared them with the team, contributing to a culture of continuous learning and growth 🧠
          - Finally, I contributed by documenting a variety of processes, such as best practices and troubleshooting guides. This has proven invaluable in fostering consistent approaches, assisting new team members, and increasing overall productivity.

      - job: "Full-Stack Web Developer"
        company: "PICSIZE"
        companyUrl: "https://picsize.com.br/"
        date: "Nov 2019 - Mar 2020"
        info:
          enable: true
          content: I was an intern for 4 months and worked more 2 months part-time.
        content: |
          During my experience as an intern, my responsibilities were more focused and adapted to my level of knowledge, with an emphasis on learning and adapting. My tasks involved supporting the development of projects, performing tests and debugging code, as well as contributing to
          the documentation and research of technical solutions.

          After I was invited to a part-time position, I was in charge of designing systems from architecture to implementation, ensuring flexibility and responsiveness of systems, monitoring performance, optimizing resources and searching for innovative solutions 🌐
          - I worked with different programming paradigms like MVC, Serverless, Event Driven, Object Driven, and also with different technologies like NodeJS, React, Redux, Redis, Styled Components, AWS EC2, AWS S3, AWS Lambda, Grafana, PostgreSQL and MongoDB.

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Bachelor's degree in Digital Games"
        school:
          name: "PUC Minas - Pontifícia Universidade Católica de Minas Gerais"
          url: "https://www.pucminas.br/"
        date: "2023 - present"
        content: |
          After I figured out that I wanted to do game development as a living and actually started working in the industry, I decided it was time to get a degree related to this area 🎮

      - title: "Bachelor's degree in Control and Automation Engineering"
        school:
          name: "UFMG - Universidade Federal de Minas Gerais"
          url: "https://ufmg.br/"
        date: "2020 - 2022 (Unfinished)"
        content: |
          I changed my major without putting much thought on it 😅, and, although I didn't liked it, I learned a lot of things I can actually translate to the game dev environment.

      - title: "Bachelor's degree in Information Systems"
        school:
          name: "UFMG - Universidade Federal de Minas Gerais"
          url: "https://ufmg.br/"
        date: "2019 - 2020 (Unfinished)"
        content: |
          I knew I wanted to major in something technology-related but I was still figuring out what exactly I wanted to do

          - I started learning web development because I thought it had an easier entry barrier to get into the job market.
          - After better thought I decided to change my major.

      - title: "Vocational degree in Mechanics, and High School"
        school:
          name: "IFES - Instituto Federal do Espírito Santo"
          url: "https://www.ifes.edu.br/"
        date: "2015 - 2018"
        content: |
          It was during high school that I came in contact with programming for the first time. I learned the basics of C++ Language and soon wanted to learn another one.

          - With the same will in mind a friend of mine started learning Python and I chose to learn Ruby, just to not copycat 😛
          - I learned it mostly by doing games using the Gosu gem, and it was pretty fun, this was also my introduction to game programming.

  # Achievements
  achievements:
    enable: false
    title: "Certificates"
    items:
      - title: Unity Junior Programmer
        content: The Unity Junior Programmer Pathway validates skills and competencies to be a proficient junior programmer writing scripts in C# to create interactive experiences with the Unity Editor.
        url: https://www.credly.com/badges/4c092772-6255-48e5-86f5-600d04ed3c9a/public_url
        image: /images/certificates/unityprog.png
      - title: Unity Essentials Pathway
        content: Unity Essentials is the pathway for interested creators who are just getting started with Unity and real-time content creation.
        url: https://www.credly.com/badges/76963fad-b54a-41fe-beda-44059fd0246f/public_url
        image: /images/certificates/unityessential.png
      - title: Node.js para iniciantes
        content: NodeBR beginner course about Node.js
        image: /images/certificates/nodebr.jpg
      - title: APIs and Microservices
        content: freeCodeCamp course on apis and microservices.
        url: "https://www.freecodecamp.org/certification/lcscout/back-end-development-and-apis"
      - title: Javascript Algorithms and Data Structures
        content: freeCodeCamp course on javascript algorithms and data structures.
        url: "https://www.freecodecamp.org/certification/lcscout/javascript-algorithms-and-data-structures"
      - title: Responsive Web Design
        content: freeCodeCamp course on responsive web design.
        url: "https://www.freecodecamp.org/certification/lcscout/responsive-web-design"
      - title: ReactJS and React Native
        content: Rocketseat course on React frameworks.
      - title: Javascript ES6+
        content: Rocketseat course on javascript ES6+

  # projects
  projects:
    enable: true
    navTitle: "Projects"
    title: "Featured Projects"
    hero:
      image: "/images/peep3432.png"
    items:
      - title: "Run01: 'til Mayhem"
        content: "Run01 is a side-scrolling endless runner game for mobile. The game is was inspired on Chrome's Dino Game, with a twist on having two runnable planes and being able to teleport between them."
        image: /images/projects/r01-Gif.gif
        featured:
          name: Demo
          link: https://github.com/lcscout/run01-unity-game/releases
        badges:
          - "Unity"
          - "Mobile"
          - "Runner"
          - "Study Project"
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=Run01%20Open%20Source%20Project
          - icon: fab fa-github
            url: https://github.com/lcscout/run01-unity-game/
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=Check+this+out:&url=https://github.com/lcscout/run01-unity-game/

      - title: Street Racing
        content: "This is a racing game where you try to beat your own time, it was a final submission project for the Unity course: Junior Programmer."
        image: /images/projects/SR-Gif_Compressed.gif
        featured:
          name: Demo
          link: https://play.unity.com/mg/other/builds-cl-1
        badges:
          - "Unity"
          - "Arcade Racing"
          - "Study Project"
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=Street%20Racing%20Open%20Source%20Project
          - icon: fab fa-github
            url: https://github.com/lcscout/street-racing-unity
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=Check+this+out:&url=https://github.com/lcscout/street-racing-unity

      - title: Warehouse Invasion
        content: "This is a FPS game with rogue-like features that I made to practice what I've learned from the Unity course: Create with Code."
        image: /images/projects/WI-Gif.gif
        featured:
          name: Demo
          link: https://play.unity.com/mg/other/webgl-builds-49946
        badges:
          - "Unity"
          - "FPS"
          - "Roguelike"
          - "Study Project"
        links:
          - icon: fab fa-github
            url: https://github.com/lcscout/wi-unity-game
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=Check+this+out:&url=https://github.com/lcscout/wi-unity-game

      - title: S.U.B.
        content: "My first official game. This is a simple \"get the treasure\" game. I also did the sprites myself, which made the project more satisfying to do."
        image: /images/projects/sub_treasure.png
        featured:
          name: Demo
          link: https://treasure-hunter-game-sub.web.app/
        badges:
          - "JavaScript"
          - "Phaser.js"
          - "Study Project"
        links:
          - icon: fab fa-github
            url: https://github.com/lcscout/sub-treasure-hunter

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: contact@lucascoutinho.me
    btnName: Mail me
    formspree:
      enable: true # `contact.email` value will be ignored
      formId: xnqkdrgb # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
      emailCaption: "Enter your email address"
      messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blog"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/lcscout
      linkedin: https://www.linkedin.com/in/lcscout/
      twitter: https://twitter.com/lcs_cout
      linktree: https://linktr.ee/lcscout

  # For index page
  indexPage:
    scroll:
      progressBar: false
      topButton: true

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
